### ISSUE TITLE
Graphical glitch when selecting area and scrolling...

### ISSUE THREAD

**Issue by AzzaAzza69** [kryslt/KControls#23] opened 2020-04-17 15:44 UTC
Selecting a range and causing a scroll (up/down/left or right) makes the DrawFocusRect paint inside the fixed row/col headings.  I think it should be clipped to the actual grid area

**Comment by AzzaAzza69** [comment] 2020-04-17 15:48
Tracked it down to:
```delphi
function TKCustomGrid.InternalGetSelectionRect(const ARect: TKGridRect): TRect;
begin
  Result := CreateEmptyRect;
  if GridRectToRect(ARect, Result, False, goRangeSelect in FOptions) then
  begin
    if FOptions * [goFixedHorzLine, goHorzLine] = [goFixedHorzLine, goHorzLine] then
      Dec(Result.Bottom, GetEffectiveRowSpacing(Max(ARect.Row1, ARect.Row2)));
    if FOptions * [goFixedVertLine, goVertLine] = [goFixedVertLine, goVertLine] then
      Dec(Result.Right, GetEffectiveColSpacing(Max(ARect.Col1, ARect.Col2)));
  end;
end;
```

if I change the False to True in the GridRectToRect() call, it doesn't do it anymore...

**Comment by kryslt** [comment] 2020-09-09 11:05
I don't see this behavior, at least not with Delphi and W10.

**Comment by AzzaAzza69** [comment] 2020-09-10 06:05
In case its an OS/Delphi specific ; I'm using Windows 7 + Delphi 2007.
I am also using these options:
```
  Options:=[goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRangeSelect, goDrawFocusSelected, goColSizing, goEditing, goClippedCells, goIndicateHiddenCells, goHeader, goIndicateSelection];
  OptionsEx:=[gxFixedCellClickSelect, gxMouseWheelScroll];
  RangeSelectStyle:=rsMS_Excel;
  ParentCtl3D:=False;
  Ctl3D:=False;
  ScrollModeHorz:=smCell;
  ScrollModeVert:=smCell;
```

**Comment by kryslt** [comment] 2020-10-14 21:17
I am not able to reproduce it (I use Windows 10 + Delphi XE or XE5, or Lazarus).
The proposed change in InternalGetSelectionRect is not the fix, just coincidence. 
That change would break other things.
Can you attach example which demonstrates this issue?

EDIT: I was able to reproduce this finally, will be fixed.

**Comment by kryslt** [comment] 2020-10-29 20:41
It seems this is Lazarus LCL only issue. I dont see similar problem with Delphi VCL. Will continue the investigations...

**Closed as completed** 2024-02-03 09:37 UTC
Labels: bug, minor
